#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -L "/app/medusa/Session.cfg" ]]; then
    ln -s /config/Session.cfg /app/medusa/Session.cfg
fi

# don't change permissions, we assume volume already has correct ownership
# permissions
# lsiown -R abc:abc \
#     /config
